// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTdp8K3RTIoKTHbFTxSjTca2quBlB8p20',
    appId: '1:42328829741:web:b1e8c1640412067a722da4',
    messagingSenderId: '42328829741',
    projectId: 'lavapp-58013',
    authDomain: 'lavapp-58013.firebaseapp.com',
    storageBucket: 'lavapp-58013.firebasestorage.app',
    measurementId: 'G-M8NRSS3YL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdvH2J3_4UAkfUDzoYCCgsmwHxKj5GCs',
    appId: '1:42328829741:android:9cac4ce6d5f7595b722da4',
    messagingSenderId: '42328829741',
    projectId: 'lavapp-58013',
    storageBucket: 'lavapp-58013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1CJkMhA4mHSzDvMQ3lqIEXvWgDS92ed4',
    appId: '1:42328829741:ios:2edb2548a233ea76722da4',
    messagingSenderId: '42328829741',
    projectId: 'lavapp-58013',
    storageBucket: 'lavapp-58013.firebasestorage.app',
    iosBundleId: 'com.example.lavapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1CJkMhA4mHSzDvMQ3lqIEXvWgDS92ed4',
    appId: '1:42328829741:ios:2edb2548a233ea76722da4',
    messagingSenderId: '42328829741',
    projectId: 'lavapp-58013',
    storageBucket: 'lavapp-58013.firebasestorage.app',
    iosBundleId: 'com.example.lavapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTdp8K3RTIoKTHbFTxSjTca2quBlB8p20',
    appId: '1:42328829741:web:09e22faa0208159e722da4',
    messagingSenderId: '42328829741',
    projectId: 'lavapp-58013',
    authDomain: 'lavapp-58013.firebaseapp.com',
    storageBucket: 'lavapp-58013.firebasestorage.app',
    measurementId: 'G-YTDV4N9XYM',
  );
}
